routes:
  - name: home
    path: :lang
    restrictions:
      lang: ru
    controller: Article
    meta:
      categories: [frontend, backend, linux]
    sitemap:
      priority: 1
      changefreq: monthly
      provider: langs
    children:
      - name: frontend
        path: frontend/:id?
        restrictions:
          id: '[\w/-]+'
        controller: Article
        meta:
          categories: [frontend]
        sitemap:
          priority: 1
          changefreq: weekly
          provider: pages
      - name: backend
        path: backend/:id?
        controller: Article
        meta:
          categories: [backend]
        sitemap:
          priority: 1
          changefreq: monthly
          provider: route
      - name: linux
        path: linux/:id?
        controller: Article
        meta:
          categories: [linux]
      - name: about
        path: about
        controller: About
      - name: page
        path: :id
        restrictions:
          id: '[\w/-]+'
        controller: Page
        sitemap:
          priority: 1
          changefreq: yearly
          provider: pages

redirects:
  php_and_somethings: /ru/backend
  javascript: /ru/frontend
  writeme: /ru/about
