routes:
  - name: home
    path: :lang
    restrictions:
      lang: ru|en
    controller: Article
    meta:
      categories: [frontend, backend, linux]
    sitemap:
      priority: 1
      changefreq: monthly
      provider: langs
    children:
      - name: frontend
        path: frontend/:id?
        restrictions:
          id: '[\w/-]+'
        controller: Article
        meta:
          categories: [frontend]
        sitemap:
          priority: 1
          changefreq: weekly
          lastmodFrom: articles/frontend
          provider: articles
      - name: backend
        path: backend/:id?
        controller: Article
        meta:
          categories: [backend]
        sitemap:
          priority: 1
          changefreq: monthly
          lastmodFrom: articles/backend
          provider: articles
      - name: devops
        path: devops/:id?
        controller: Article
        meta:
          categories: [devops]
        sitemap:
          priority: 1
          changefreq: monthly
          lastmodFrom: articles/devops
          provider: articles
      - name: about
        path: about
        controller: About
        sitemap:
          priority: 1
          changefreq: yearly
          lastmodFrom: pages/about
      - name: page
        path: :id
        restrictions:
          id: '[\w/-]+'
        controller: Page
        sitemap:
          priority: 1
          changefreq: yearly
          provider: pages

redirects:
  php_and_somethings: /ru/backend
  javascript: /ru/frontend
  linux: /ru/devops
  writeme: /ru/about
  main: /ru
